# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('desc', models.CharField(default='商品的描述信息', max_length=1000, verbose_name='描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/goods/', verbose_name='图片')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.CharField(default='商品类型描述', max_length=200, verbose_name='描述')),
                ('flag', models.IntegerField(default=0, verbose_name='标记')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/goods_type/', verbose_name='图片')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
    ]
