# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.GoodsType'),
            preserve_default=False,
        ),
    ]
