# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderinfo_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
