# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_author_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '书生', 'verbose_name_plural': '书生'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
