# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181116_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['age'], 'verbose_name': '书生', 'verbose_name_plural': '书生'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publicate_date'], 'verbose_name': '小黄书', 'verbose_name_plural': '小黄书'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
