# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人性', 'verbose_name_plural': '人性'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
