# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-14 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
