# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181116_1149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
