# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181116_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='isActives',
            new_name='isActive',
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
