# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20181116_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['city'], 'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
