# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181116_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '相公',
                'db_table': 'wife',
                'ordering': ['age'],
                'verbose_name': '相公',
            },
        ),
    ]
