# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_author_publisher01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='publisher01',
            new_name='publishers',
        ),
    ]
