# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('cellphon', models.CharField(max_length=20, null=True, verbose_name='电话')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
