# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
