# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171107_1732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
