# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_book_publisher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='index_author',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='index_publisher',
        ),
        migrations.AlterModelTable(
            name='wife',
            table='index_wife',
        ),
    ]
