# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20181116_1945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
