# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-21 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsType',
            new_name='GoodType',
        ),
        migrations.AlterModelTable(
            name='goodtype',
            table='good_type',
        ),
    ]
