# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20181116_1449'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author1',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book1',
        ),
    ]
