# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_wife_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'ordering': ['age'], 'verbose_name': '娘子', 'verbose_name_plural': '娘子'},
        ),
    ]
