# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20181119_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publishers',
        ),
    ]
