# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_remove_author_publishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publishers',
            field=models.ManyToManyField(to='index.Publisher'),
        ),
    ]
