# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_author_publishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publishers',
        ),
    ]
