# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-19 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='类型图片'),
        ),
    ]
